services:
    _defaults:
        autowire: true
        autoconfigure: true

    ComposerFix\Command\:
        resource: '../src/ComposerFix/Command/*'
        tags:
            - { name: 'console.command' }

    ComposerFix\EventSubscriber\InstallSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
