services:
    _defaults:
        autowire: true
        autoconfigure: true

    FixComposer\Command\:
        resource: '../src/FixComposer/Command/*'
        tags:
            - { name: 'console.command' }

    FixComposer\EventSubscriber\InstallSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
